### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by annahung31** [idiap/fast-transformers#19]
Hi, thanks for the great work!

I install the package successfully but encounter an error during training:

`File "/home/annahung/189nas/2020/fast_remi/linear_transformer/model.py", line 294, in train
    predict = model(batch_x)
  File "/home/annahung/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/annahung/189nas/2020/fast_remi/linear_transformer/modules.py", line 108, in forward
    decoder_y_ = self.transformer(batch_x_embed, attn_mask=attn_mask) #shape=(bs, num_heads*value_dim)
  File "/home/annahung/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/annahung/.local/lib/python3.6/site-packages/fast_transformers/transformers.py", line 131, in forward
    x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
  File "/home/annahung/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/annahung/.local/lib/python3.6/site-packages/fast_transformers/transformers.py", line 77, in forward
    key_lengths=length_mask
  File "/home/annahung/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/annahung/.local/lib/python3.6/site-packages/fast_transformers/attention/attention_layer.py", line 98, in forward
    key_lengths
  File "/home/annahung/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/annahung/.local/lib/python3.6/site-packages/fast_transformers/attention/causal_linear_attention.py", line 74, in forward
    values
  File "/home/annahung/.local/lib/python3.6/site-packages/fast_transformers/attention/causal_linear_attention.py", line 24, in causal_linear
    return V_new.permute(0,2,1,3).contiguous()
RuntimeError: CUDA error: an illegal memory access was encountered`

I can run other PyTorch models but not with fast-transformer...
I read issue  #12 and consider this might also be caused by the CUDA version **(CUDA 10.1, V10.1.105).**
Any suggestions to solve this? Thanks a lot.

**Comment by annahung31** [comment]
Oh, I found a solution! It turns out to be a PyTorch problem. 
To whom encounter the same question, I solved the problem by changing the way to specify a GPU: `torch.cuda.set_device(1)` 
Reference: https://github.com/pytorch/pytorch/issues/21819
